// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_scrMain_screen_init(void)
{
    ui_scrMain = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_scrMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pnlMain = lv_obj_create(ui_scrMain);
    lv_obj_set_width(ui_pnlMain, lv_pct(100));
    lv_obj_set_height(ui_pnlMain, lv_pct(100));
    lv_obj_set_align(ui_pnlMain, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_pnlMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    setupCountButton(ui_pnlMain);
}

void setupCountButton(lv_obj_t * ui_pnlMain)
{
    ui_btnCount = lv_button_create(ui_pnlMain);
    lv_obj_set_width(ui_btnCount, 150);
    lv_obj_set_height(ui_btnCount, 50);
    lv_obj_set_align(ui_btnCount, LV_IMAGE_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_btnCount, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnCount, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblButton = lv_label_create(ui_btnCount);
    lv_obj_set_width(ui_lblButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblButton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblButton, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblButton, "Roll");

    ui_lblCountValue = lv_label_create(ui_pnlMain);
    lv_obj_set_width(ui_lblCountValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCountValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCountValue, 0);
    lv_obj_set_y(ui_lblCountValue, 40);
    lv_obj_set_align(ui_lblCountValue, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblCountValue, "0");
    // lv_obj_set_style_text_font(ui_lblCountValue, &lv_font_montserrat_48, 0);

    lv_obj_add_event_cb(ui_btnCount, ui_event_btnCount, LV_EVENT_ALL, NULL);
}
